[build]
  publish = "dist/client"
  command = "npm run build"
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://ustadgo.vercel.app/api"
